### ISSUE TITLE
Ring definition approaches

### ISSUE THREAD

**Issue by WojciechKarpiel** [JetBrains/arend-lib#16]
Hi!
I've read in the Arend tutorial that you solve the "diamond problem" for implementing ring structure by copying structure definitions:
Tutorial: https://arend-lang.github.io/documentation/tutorial/PartI/records
Ring definition: https://github.com/JetBrains/arend-lib/blob/master/src/Algebra/Ring.ard
Root of copied classes: https://github.com/JetBrains/arend-lib/blob/master/src/Algebra/Pointed.ard

My questions are:
Why was this approach choosen? What are pros/conses in comparision to other solutions?
In particular, I'm curious what do you think about Agda standard library's approach.

I very much like the approach that Agda's standard library uses:
Split classes into structure definitions (where 0/1 and +/* are class parameters) and structure bundles (where 0/1 and +/* are class fields).
Structure definition (IsRing): https://github.com/agda/agda-stdlib/blob/master/src/Algebra/Structures.agda#L432
Bundle definition (Ring, which uses IsRing internally): https://github.com/agda/agda-stdlib/blob/master/src/Algebra/Bundles.agda#L623

Regards,
Wojciech

**Comment by ice1000** [comment]
Right now, Arend classes only allow one classification field, while Agda seems to support no matter how many.

**Comment by WojciechKarpiel** [comment]
I see, thanks for answering!
Still, what are advantages and disadvantages of `\extend`ing two copied hierarchies instead of:
* making the Ring `\extend` only the `BaseSet`,
* and using class fields to store the abelian group and the monoid?

This way the abelian group and the monoid could share a single hierarchy.

If I'm unclear, this code might present my intentions better:
https://gist.github.com/WojciechKarpiel/e9d60b268ee5dc39d314fb2ecd59a64e

**Comment by valis** [comment]
If we put the group and monoid structures to fields, then we need to add another fields (or functions) with names `*` and `+` that evalute to operations we need. The problem is that they will be evaluated during normalization and will be printed not in a nice way.

**Comment by valis** [comment]
Btw, this is not a good place to ask questions. Try something from this list https://github.com/JetBrains/Arend#community next time.
