### ISSUE TITLE
Feature request: automatically generate "equals" definitions

### ISSUE THREAD

**Issue by tonyxty** [JetBrains/arend-lib#25]
The principle "properties are irrelevant when proving equalities between two instances of a class" can be automated.

Consider for example the definition of `Monoid` in the standard library.
````arend
\class Monoid \extends Pointed {
  | \infixl 7 * : E -> E -> E
  | ide-left {x : E} : ide * x = x
  | ide-right {x : E} : x * ide = x
  | *-assoc {x y z : E} : (x * y) * z = x * (y * z)
}
````
where `E` is a `\Set`.  Arend can infer that the latter three fields are in fact propositions, and we can then show that two `Monoid`s are equal as long as the binary operators are equal (`Monoid.equals` in the standard library).  This is a very common situation that applies to all algebraic structures, and it would be nice if it can be automatically generated with a meta.

**Comment by valis** [comment]
This has been implemented in the extensionality meta.
