### ISSUE TITLE
Prove that the radical of the ideal generated by two elements is equal to the radical of the ideal generated by powers of these elements

### ISSUE THREAD

**Issue by valis** [JetBrains/arend-lib#41]
This is [AG.Scheme/pow-lin-comb](https://github.com/JetBrains/arend-lib/blob/4ea97da483c5bb2e6a22c8d09c03becf17756c7e/src/AG/Scheme.ard#L153). Explicitly, this just means that if `e^k = a*c + b*d`, then there are `t`, `s`, and `l` such that `e^l = t*a^n + s*b^m`.

**Comment by TurtlePU** [comment]
I'll take it; I am not going to provide a generalization for now, though.
