### ISSUE TITLE
Prove that the ideal generated by a two-element set consists of linear combinations of those elements

### ISSUE THREAD

**Issue by valis** [JetBrains/arend-lib#43]
This is [Algebra.Ring.Ideal/Ideal.closure2-lem](https://github.com/JetBrains/arend-lib/blob/4ea97da483c5bb2e6a22c8d09c03becf17756c7e/src/Algebra/Ring/Ideal.ard#L81). This can be generalized to any finite set of elements.

**Comment by TurtlePU** [comment]
I'll do it! Will PR in a while.
