### ISSUE TITLE
Prove a lemma about homogeneous decomposition

### ISSUE THREAD

**Issue by valis** [JetBrains/arend-lib#57]
Let R be a graded ring. Suppose we have a homogeneous element x, which is equal to \sum_{1 <= i <= n} a_i b_i, where a_i are homogeneous. Then we can decompose b_i into homogeneous elements b_i^1 + ... + b_i^{k_i}. By uniqueness of decomposition of x, there is at most one b_i^{j_i} such that a_i * b_i^{j_i} is non-zero. It follows that x is equal to \sum_{1 <= i <= n} a_i b'_i, where b'_i are homogeneous. [This goal](https://github.com/JetBrains/arend-lib/blob/9fddaa74d21a4ed840563230f6f1d702f1cbafc5/src/AG/Projective.ard#L122) should prove this equality.

**Comment by ice1000** [comment]
Let $R$ be a graded ring. Suppose we have a homogeneous element x, which is equal to $\sum_{1 \leq i \leq n} a_i b_i$, where $a_i$ are homogeneous. Then we can decompose $b_i$ into homogeneous elements $b_i^1 + ... + b_i^{k_i}$. By uniqueness of decomposition of $x$, there is at most one $b_i^{j_i}$ such that $a_i \times b_i^{j_i}$ is non-zero. It follows that $x$ is equal to $\sum_{1 \leq i \leq n} a_i b'_i$, where $b'_i$ are homogeneous. [This goal](https://github.com/JetBrains/arend-lib/blob/9fddaa74d21a4ed840563230f6f1d702f1cbafc5/src/AG/Projective.ard#L122) should prove this equality.

**Comment by valis** [comment]
@ice1000 How did you do that?)

**Comment by ice1000** [comment]
> @ice1000 How did you do that?)

https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/writing-mathematical-expressions
